Add camomile
rehypejs/camomile pull request #1
Opened 2023-09-15 10:07 UTC by Murderlon

As discussed in the RFC https://github.com/unifiedjs/rfcs/pull/9, here is the implementation of camomile, our Node.js image proxy to work together with [`rehype-github-image`](https://github.com/rehypejs/rehype-github/tree/main/packages/image).

## How it works

camomile works together with `rehype-github-image`, which does the following at build time:

1.  The original URL in the content is parsed.
2.  An [HMAC][] signature of the URL is generated.
3.  The URL and HMAC are encoded.
4.  The encoded URL and HMAC are placed into the expected format, creating the signed URL.
5.  The signed URL replaces the original image URL.

After your web app serves the content to the user, camomile takes over:

1.  The client requests the signed URL from camomile.
2.  camomile validates the [HMAC][], decodes the URL, then requests the content from
    the origin server and streams it to the client.

## Features

- A `maxSize` option in bytes to limit the downloading of resources (failing if exceeded)
- Security. Only HTTP(s) is allowed, no other protocols. Protection built-in for [Server-Side Request Forgery](https://owasp.org/www-community/attacks/Server_Side_Request_Forgery).
- Filtering of headers. Request headers from the client which we want to pass on to the remote server and response headers from the remote server to the client.

## Future additions

- Allow audio and video content through options
- Respect forwarded headers
- Structured logging (with log levels)
- Add events (`server.on('foo', () => {})`)
- Compression

## Time spent

Four and a half full working days.

[HMAC]: https://en.wikipedia.org/wiki/HMAC

2023-09-15 11:18 UTC, wooorm reviewed
Super exciting! I’ve pinged the `camomile` npm owner again!

First part of nits :)

2023-09-15 11:18 UTC, wooorm commented on .github/workflows/main.yml
> +      - run: npm test
should there be a coverage test / codecov integration?

2023-09-15 11:18 UTC, wooorm commented on .prettierrc.json
> +  "proseWrap": "always"
a) I prefer putting config in `package.json` when possible, and this should be possible there
b) can you sort the keys alphabetically?

2023-09-15 11:18 UTC, wooorm commented on .remarkrc.js
> +export default remarkConfig
Same, put this in `package.json`? Why not?

2023-09-15 11:18 UTC, wooorm commented on index.js
> +export * from './lib/constants.js'
This should probably export `Options` (currently called `Config`) from `server.js`, so folks can import that type? Anything else that needs exporting???

2023-09-15 11:18 UTC, wooorm commented on index.js
> +export * from './lib/constants.js'
```suggestion
export {DEFAULT_HEADERS, REQUEST_HEADERS, RESPONSE_HEADERS, IMAGE_MIME_TYPES} from './lib/constants.js'
```

Beter to use actual export identifiers than a `*`

Should all these constants be exported? For what?

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +/** @constant */
I don‘t think `@constant` does anything in TS? What is the intention?

Currently, TS infers this as: `const DEFAULT_HEADERS: {'X-Frame-Options': string;`...}`, is that intentional? Should it be a record of strings to strings? Should it be readonly?

And: should they be exposed?

(same for all other exported records)

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +  // where an attacker might use an iframe to overlay a legitimate page over a deceptive page.
```suggestion
  /**
   * Ensures that the page can’t be displayed in a frame,
   * regardless of where the request came from.
   * It’s a security feature to prevent “clickjacking” attacks,
   * where an attacker might use an iframe to overlay a legitimate page over a
   * deceptive page.
   */
```

Actual doc comments, actual unicode punctuation characters instead of typewriter ASCII

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +  // rather than sanitizing the page, the browser will prevent rendering of the page entirely.
```suggestion
  /**
   * The browser should enable the XSS filter and if a XSS attack is detected,
   * rather than sanitizing the page, the browser will prevent rendering of the
   * page entirely.
   */
```

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +  // files as a different MIME type, which can be exploited in attacks.
```suggestion
  /**
   * Trust what the server says and not to perform MIME type sniffing.
   * This can prevent certain security risks where the browser might interpret
   * files as a different MIME type, which can be exploited in attacks.
   */
```

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +  // which usually means from within the HTML itself rather than from external files.
```suggestion
  /**
   * By default, do not load content from any source (`default-src 'none'`),
   * images can be loaded from `data:` URLs (like Base64 encoded images),
   * and styles can be loaded inline (`style-src 'unsafe-inline'`),
   * which usually means from within the HTML itself rather than from external
   * files.
   */
```

Docs, and use markdown code for code

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +  // their browser will automatically upgrade the request to HTTPS.
```suggestion
  /**
   * This header is often called HSTS (HTTP Strict Transport Security).
   * It’s a security feature that ensures a website can only be accessed over
   * HTTPS instead of HTTP.
   * The `max-age` parameter specifies how long (in seconds) the browser should
   * remember to enforce this policy.
   * The `includeSubDomains` directive extends this rule to all subdomains of
   * the domain sending the header.
   * This ensures that even if a user tries to access the site or its
   * subdomains via HTTP,
   * their browser will automatically upgrade the request to HTTPS.
   */
```

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> + */
```suggestion
/**
 * HTTP request headers that are acceptable to pass from the client to the
 * remote server.
 * Only those present and true are forwarded.
 * 
 * @type {Readonly<Map<string, boolean>>}
 */
```

Docs, readonly, explicit type

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +  ['Accept-Encoding', false], // images (aside from xml/svg), don't typically benefit from compression
```suggestion
  // No `Accept-Encoding` because images (other than from XML or SVG), don’t
  // typically benefit from compression:
  ['Accept-Encoding', false],
```

Casing, sentence, capitalize acronym, smart apostrophe

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +  ['Range', true] // required to support safari byte range requests for video
```suggestion
  // `Range` is used by Safari for byte range requests on video:
  ['Range', true],
  // No `X-Forwarded-For` because ???
  ['X-Forwarded-For', false]
```

Sorting, casing, code. Note: why no `x-forwarded-for`?

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +])
```suggestion
/**
 * HTTP response headers that are acceptable to pass from the remote server to
 * the client.
 * Only those present and true are forwarded.
 *
 * @type {Readonly<Map<string, boolean>>}
 */
export const RESPONSE_HEADERS = new Map([
  // `Accept-Ranges` is used by Safari for byte range requests on video:
  ['Accept-Ranges', true],
  ['Cache-Control', true],
  ['Content-Length', true],
  ['Content-Encoding', true],
  ['Content-Range', true],
  ['Content-Type', true],
  ['ETag', true],
  ['Expires', true],
  ['Last-Modified', true],
  // `Server` is disallowed because ???
  ['Server', false],
  ['Transfer-Encoding', true]
])
```

Same as above, remove random blank line, sorting. Note: why no server?

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +/** @constant */
```suggestion
/**
 * MIME types that we allow.
 * 
 * @type {ReadonlyArray<string>}
 */
```


Docs, explicit readonly.

2023-09-15 11:18 UTC, wooorm commented on lib/constants.js
> +]
Note: I feel like the UPPERCASE stuff for “constants” like this is a bit archaic.

I prefer stuff like `defaultMimeTypes`, corresponding to say a `options.mimeTypes`; `defaultResponseHeaders` and `options.responseHeaders`, etc.

2023-09-15 11:58 UTC, Murderlon commented on .github/workflows/main.yml
> +      - run: npm test
My humble opinion: code coverage is valuable for parsers and algorithms, a lot less interesting for for applications / servers.

2023-09-15 11:59 UTC, Murderlon commented on index.js
> +export * from './lib/constants.js'
Can also not export the constants indeed until people ask for it for some reason.

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +import {IMAGE_MIME_TYPES} from './constants.js'
```suggestion
import dns from 'node:dns/promises'
import ipaddr from 'ipaddr.js'
import {fetch} from 'undici'
import {IMAGE_MIME_TYPES} from './constants.js'
```

Sorting, no blank lines.

Q: As Node 16 is not maintained, we can go with Node 18 as a base here, which supports `fetch`. I wouldn’t do that for the unified plugins / utilities as half of them is just released with Node 16 support, so having mixed 16 and 18 minimum is complex, but as this is a new project intended for a very different place, we could do it here?

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +   */
```suggestion
  /**
   * Create an HTTP error.
   * 
   * @param {number} statusCode
   *   Status code.
   * @param {string} message
   *   Message.
   * @returns
   *   HTTP error.
   */
```

Not supor useful, but nice to have some docs.

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +    // Captures the stack trace, excluding the constructor call from the stack trace.
```suggestion
    // Exclude the constructor call from the stack trace.
```

That it captures the stack trace is evident from the code, the reason why this is here is useful to have in a comment though.

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +export class HttpError extends Error {
Maybe `CamomileError` here? `HttpError` is quite non-descript

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +export class SafeHttpClient {
1. I’m not sure this needs to be a class? Particularly if it has one static member, the construct accepts one option field?
2. The name, not sure “safe” is needed on the class, and what is “client” here?

I’d almost call this file `utilities.js`, which exports `checkUrl` and `safeFetch`, where `safeFetch` accepts `maxSize` in its options?

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +    const {protocol, hostname} = validUrl
```suggestion
  /**
   * Check that the URL is valid, the prototol is allowed, and that the host is
   * a safe unicast address.
   *
   * @param {string} url
   *   URL to check.
   * @returns {Promise<URL>}
   *   URL object.
   */
  static async checkUrl(url) {
    const validUrl = new URL(url)
    const {hostname, protocol} = validUrl
```

Docs, sorting.

Q: when a function is called `checkUrl`, I‘d assume it would only *check* and return a boolean, instead of returning a parsed URL. Throwing errors in “check” also seems not intuitive to me.

Alternatively, I can understand a `checkUrl` that throws errors and returns `Promise<undefined>`, aka nothing.

Last, it might make sense to use different status codes for different errors? Simplest would perhaps be to inline it in `server.js`. Or throw `HttpError`s and use the `error.statusCode || 400` on them in `server.js`?

Quickly thinking, maybe:
invalid url -> 400
bad protocol -> 403
bad url host (1, dns.lookup) -> 400
bad url host (2, ipaddr) -> 403

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +    }
```suggestion
    // Only allow known safe protocols.
    if (!allowedProtocols.has(protocol)) {
      throw new Error('Bad protocol')
    }
```

Comment, and move a `const allowedProtocols = new Set(['http:', 'https:'])` to the top scope perhaps? As it’s a sort of constant?

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +   */
```suggestion
  /**
   * Fetch a safe URL, presumed to be an image.
   * 
   * @param {URL | string} url
   *   URL.
   * @param {import('undici').RequestInit} options
   *   Configuration, passed through to `fetch`.
   * @returns {Promise<{buffer?: Buffer, headers: import('undici').Headers}>}
   *   Buffer of response (except when `HEAD`) and headers.
   */
```

Docs.

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +      response = await fetch(redirectedUrl, {
```suggestion
      const redirectedUrl = response.headers.get('location')

      if (!redirectedUrl) {
        throw new HttpError(400, 'Missing `Location` header')
      }

      await SafeHttpClient.checkUrl(redirectedUrl)

      response = await fetch(redirectedUrl, {
```

Handle potential error

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +    if (!contentType || contentType.length === 0) {
```suggestion
    if (!contentType) {
```

Empty is checked by `!`

2023-09-15 12:17 UTC, wooorm commented on lib/safe-http-client.js
> +    /** @type {Uint8Array[]} */
```suggestion
    /** @type {Array<Buffer>} */
```

There are some small differences between the two. I think these are actually buffer objects, so best to use that more specific child class

2023-09-15 12:29 UTC, Murderlon commented on lib/safe-http-client.js
> +import {IMAGE_MIME_TYPES} from './constants.js'
I needed `undici` anyway because of `MockAgent` in tests and since the package is there, might as well use the `fetch` export and not rely on a experimental Node >18 only feature. I can remove it, but it comes for free at this point.

2023-09-15 12:35 UTC, Murderlon commented on lib/safe-http-client.js
> +export class HttpError extends Error {
It's not used outside the context of this server, so everything is inherently camomile related. Within this server, this is an HTTP error, so I think it's fine.

2023-09-15 12:40 UTC, Murderlon commented on lib/safe-http-client.js
> +export class SafeHttpClient {
It is "safe" because it won't allow you to make dangerous HTTP requests and prevents large payload attacks. It's a client because we are on the receiving end. 

Calling things "utils" / "utilities" is my personal pet peeve though, as it's generic not intention revealing naming.

I don't have a strong opinion on it being a class or not. It feels okay in this context, functions are also okay.

2023-09-15 12:59 UTC, Murderlon commented on lib/safe-http-client.js
> +    const {protocol, hostname} = validUrl
> Throwing errors in “check” also seems not intuitive to me

For me it's the opposite, I do expect errors in this function. 

> Alternatively, I can understand a `checkUrl` that throws errors and returns `Promise<undefined>`, aka nothing.

That seems fine yes!

>  Last, it might make sense to use different status codes for different errors?

I don't think so, they are all client-side mistakes (intentional or not). I'm also happier not exposing too many details of the internals and rejecting everything "bad" regarding URLs with `400`.

2023-09-15 13:00 UTC, Murderlon commented on lib/safe-http-client.js
> +    }
I think I prefer it the way it is. It's a simple inline check, no need to expose it globally in the file or function scope.

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +} from './constants.js'
```suggestion
import crypto from 'node:crypto'
import {EventEmitter} from 'node:events'
import http from 'node:http'
import net from 'node:net'
import url from 'node:url'
import {Headers} from 'undici'
import {
  DEFAULT_HEADERS,
  REQUEST_HEADERS,
  RESPONSE_HEADERS
} from './constants.js'
import {HttpError, SafeHttpClient} from './safe-http-client.js'
```

Sorting, no blank lines

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> + */
```suggestion

/**
 * @typedef Config
 *   Configuration.
 * @property {string} HMACKey
 *   Secret.
 * @property {string} serverName
 *   Name of server; used in `Headers` and `Via`.
 * @property {number | undefined} [maxSize]
 *   Max size in bytes per resource to download (default: `undefined`);
 *   If passed, sends a `404` if exceeded.
 */
```

More docs.

Q1: I prefer the name `Options` for such types.
Q2: how about `secret`, just like `rehype-github-images`, for the shared secret? Otherwise, I prefer `hmacKey`
Q3: I don’t think `serverName` is actually “checked” (current text?), it’s sent along though?
Q4: `maxSize` currently seems to send a 404?
Q5: should we set a default `maxSize`?

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +    bytes.push(parseInt(hex.substr(i, 2), 16))
```suggestion
    bytes.push(parseInt(hex.slice(i, 2), 16))
```

`substr` is deprecated, I think this works.
But: `Buffer.from('68747470733a2f2f666f6f2e6261722f696d6167652e706e67', 'hex').toString()` also decodes, so you can drop this function

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +      }
```suggestion
      const value = incomingHeaders.get(key.toLowerCase())

      if (value !== null && value !== undefined && bool) {
        filteredHeaders[key] = value
      }
```

Solve the type error, and don’t first check and then get, which is an antipattern: get and then check whether it’s defined or not.

Two Qs:
a) are the headers case insensitive? If so, that should likely be noted in `constant.js`. I’d also then say we shouldn’t case them there at all?
b) This also seems like the `bool` isn’t useful: `false` is treated the same as not being included in `allowedHeaders` at all. Perhaps sets are better?

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +   * @param {Config} config
```suggestion
   * @param {Readonly<Config>} config
```

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +    this.config.serverName ??= 'camo'
```suggestion
    this.config = {...config, serverName: config?.serverName || 'camo'}
```

Do not mutate the given object

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +   */
```suggestion
  /**
   * Start the server.
   * 
   * @param {Parameters<InstanceType<typeof net.Server>['listen']>} args
   *   Arguments passedf to `net.Server.listen`.
   * @returns {net.Server}
   *   Server.
   */
```

a) docs, b) `@public` is the default

Q: Should it be possible to stop the server?

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +    const paths = url.parse(req.url)?.path?.split('/')
```suggestion
    const paths = url.parse(req.url || '')?.path?.split('/')
```

I think this will solve your TS issue fine?

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +      return this.write(res, 400, err.message)
```suggestion
      const exception = /** @type {Error} */ (err)
      return this.write(res, 400, exception.message)
```

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +        // @ts-ignore we can convert req.headers to Headers
```suggestion
        // @ts-expect-error: `IncomingHttpHeaders` can be passed to `Headers`
```

a) use ts-expect-error, which results in an error if it doesn’t error, that way, when Node types are fixed, we get an error, and can remove it

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +  verifyHMAC(receivedDigest, hex) {
Should be spelled `verifyHmac`

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +    const decodedUrl = originalUrlBuffer.toString('utf-8')
```suggestion
    // Hex-decode the URL
    const decodedUrl = Buffer.from(hex, 'hex').toString()
```

Simplify, buffers can hex decode. The `utf-8` part is the default also.

2023-09-15 13:02 UTC, wooorm commented on lib/server.js
> +    }
```suggestion
   * @param {Buffer | string} body
   * @param {Record<string, string | undefined>} [headers]
   * @private
   */
  write(res, status, body, headers = DEFAULT_HEADERS) {
    if (status !== 204) {
      headers['Content-Length'] = String(Buffer.byteLength(body, 'utf8'))
    }
```

Not sure what the actual valid `body`s are that you expect, but `Buffer | string` probably allows most cases? Is it allowed to be `undefined`? These are the ones allowed by `Buffer.byteLength`: `NodeJS.ArrayBufferView | ArrayBuffer | SharedArrayBuffer | string`.

2023-09-15 13:02 UTC, wooorm commented on package.json
> +    "typescript": "^5.2.2"
```suggestion
  "dependencies": {
    "ipaddr.js": "^2.0.0",
    "undici": "^5.0.0"
  },
  "devDependencies": {
    "@types/node": "^18.0.0",
    "prettier": "^3.0.0",
    "remark-cli": "^11.0.0",
    "remark-preset-wooorm": "^9.0.0",
    "typescript": "^5.0.0"
```

Use loose version ranges if unknown. It creates cleaner package locks, and makes it easier for package managers to resolve conflicts

2023-09-15 13:25 UTC, wooorm commented on readme.md
> +server.listen({host, port})
```suggestion
import {Server} from 'camomile'

const HMACKey = process.env.CAMOMILE_HMAC_KEY

if (!HMACKey) throw new Error('Missing `CAMOMILE_HMAC_KEY` in environment')

const server = new Server({HMACKey})

server.listen({host: '127.0.0.1', port: 1080})
```

`require` doesn’t work; fix typescript issue; remove unneeded variables.

Note: a) I think the secret should be called `secret`, b) `serverName` is currently typed as being required, it should be optional (the rest of the code treats it as such)

2023-09-15 13:25 UTC, wooorm commented on readme.md
> +Limit the maximum size of a resource in bytes (`number`, default: `null`).
```suggestion
Limit the maximum size of a resource in bytes (`number`, default: `undefined`).
```

Don’t use `null` if possible, `null` isn‘t allowed as a value according to the types, `undefined` is also closer to not settings something

2023-09-15 13:25 UTC, wooorm commented on readme.md
> +app.listen(port, host)
```suggestion
import express from 'express'
import {Server} from 'camomile'

const HMACKey = process.env.CAMOMILE_HMAC_KEY
if (!HMACKey) throw new Error('Missing `CAMOMILE_HMAC_KEY` in environment')

const host = '127.0.0.1'
const port = 1080
const app = express()
const uploadApp = express()
const camomile = new Server({HMACKey})
uploadApp.all('*', camomile.handle.bind(camomile))

app.use('/uploads', uploadApp)
app.listen(port, host)

console.log('Listening on `http://' + host + ':' + port + '/uploads/`')
```

a) esm, b) type error, c) add feedback to let users know it works

2023-09-15 13:25 UTC, wooorm commented on readme.md
> +server.listen(port)
```suggestion
import http from 'node:http'
import url from 'node:url'
import {Server} from 'camomile'
import Koa from 'koa'

const HMACKey = process.env.CAMOMILE_HMAC_KEY
if (!HMACKey) throw new Error('Missing `CAMOMILE_HMAC_KEY` in environment')

const port = 1080
const app = new Koa()
const appCallback = app.callback()
const camomile = new Server({HMACKey})

const server = http.createServer((req, res) => {
  const urlPath = url.parse(req.url || '').pathname || ''

  // handle any requests with the `/files/*` pattern
  if (/^\/files\/.+/.test(urlPath.toLowerCase())) {
    return camomile.handle(req, res)
  }

  appCallback(req, res)
})

server.listen(port)
```

esm, type errors

2023-09-15 13:25 UTC, wooorm commented on readme.md
> +})
```suggestion
import createFastify from 'fastify'
import {Server} from 'camomile'

const HMACKey = process.env.CAMOMILE_HMAC_KEY
if (!HMACKey) throw new Error('Missing `CAMOMILE_HMAC_KEY` in environment')

const fastify = createFastify({logger: true})
const camomile = new Server({HMACKey})

/**
 * Add `content-type` so fastify forewards without a parser to the leave body untouched.
 *
 * @see https://www.fastify.io/docs/latest/Reference/ContentTypeParser/
 */
fastify.addContentTypeParser(
  'application/offset+octet-stream',
  (request, payload, done) => done(null)
)

/**
 * Use camomile to handle preparation and filehandling requests.
 * `.raw` gets the raw Node HTTP request and response objects.
 *
 * @see https://www.fastify.io/docs/latest/Reference/Request/
 * @see https://www.fastify.io/docs/latest/Reference/Reply/#raw
 */
fastify.all('/files', (req, res) => {
  camomile.handle(req.raw, res.raw)
})
fastify.all('/files/*', (req, res) => {
  camomile.handle(req.raw, res.raw)
})

fastify.listen({port: 3000}, (err) => {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
})
```

ESM, docs, do not use deprecated API signature

2023-09-15 13:25 UTC, wooorm commented on tsconfig.json
> +  "exclude": ["coverage/", "node_modules/", "rehype-github-image/", "test.js"],
Why are the tests not checked?

2023-09-15 13:48 UTC, Murderlon commented on lib/server.js
> + */
> Q1: I prefer the name `Options` for such types.

👍 

> Q2: how about `secret`, just like `rehype-github-images`, for the shared secret? Otherwise, I prefer `hmacKey`

👍 

> Q3: I don’t think `serverName` is actually “checked” (current text?), it’s sent along though?

Checked for what? It being a string you mean?

> Q4: `maxSize` currently seems to send a 404?

Yes thinking to change it to `413` (Content Too Large).

> Q5: should we set a default `maxSize`?

Probably a good idea yes. Here is what GPT thinks the default should be: https://chat.openai.com/share/188485eb-b6ee-4957-a96a-c112c1582544

2023-09-15 13:58 UTC, Murderlon commented on lib/server.js
> +      }
> a) are the headers case insensitive? If so, that should likely be noted in `constant.js`. I’d also then say we shouldn’t case them there at all?

According to the HTTP spec it doesn't matter. But it's definitely canonical to use Pascal-Case.

> This also seems like the `bool` isn’t useful: `false` is treated the same as not being included in `allowedHeaders` at all. Perhaps sets are better?

It's handy to explicitly indicate what is not allowed and when respecting forwarded headers are allowed, we could change the value to true based on some checks. But `Set` may be good too here yes.

2023-09-15 14:00 UTC, Murderlon commented on lib/server.js
> +   */
Return type is already inferred and it's [generally the consensus to not add it unnecessarily](https://www.youtube.com/watch?v=nwSe95uFN8E).

You can do whatever you want with the server in the same way as you would when using `net.Server`

```js
const camomile = new Server({HMACKey})
const server = camomile.listen()

await server.close()
```

2023-09-15 14:25 UTC, Murderlon commented on package.json
> +    "typescript": "^5.2.2"
I don't understand why you would do this. GPT can't come up with the benefits either:

https://chat.openai.com/share/5e4aa769-4e0b-4214-a966-fec85c82cc2f

2023-09-15 15:07 UTC, ChristianMurphy commented on package.json
> +    "typescript": "^5.2.2"
It allows package managers to deduplicate versions.
If a dependency is already being used without issue, there is no reason to force npm/yarn to install two copies of it.

2023-09-16 08:44 UTC, Murderlon commented on package.json
> +    "typescript": "^5.2.2"
That is a trade off not worth making in my opinion. Rounding down may introduce bugs or missing features if a package was at ^2.1.0 instead of ^2.0.0, there's usually a reason for that. Besides we can't guarantee it will dedupe versions in all cases. Sounds like taking risks for the small gain of using less disk space. Which is practically a XY problem, if disk space on your personal computer is a worry there are many ways to deal with that other than making our dependencies less predictable and safe.

2023-09-18 09:52 UTC, Murderlon commented
I think this is ready now. All open comments have a response from me now. I think most open comments are some subjective opinions not blocking for merge. There is the comment about rounding down versions numbers, which I find odd but willing to change of course if that is considered blocking.

2023-09-18 15:17 UTC, remcohaszing requested changes

2023-09-18 15:17 UTC, remcohaszing commented on lib/safe-http-client.js
> +    }
I would go with this:

```suggestion
    // Don't allow aother protocols like file:// URLs
    if (protocol !== 'http:' && protocol !== 'https:') {
      throw new Error('Bad protocol')
    }
```

I’m not sure if v8 optimizes this, but it feels redundant to create an intermediate array.

The same pattern is repeated below.

2023-09-18 15:17 UTC, remcohaszing commented on lib/safe-http-client.js
> +export class SafeHttpClient {
I generally prefer plain objects and functions. The only exception that comes to mind is custom errors.

2023-09-18 15:17 UTC, remcohaszing commented on lib/safe-http-client.js
> +      var {address} = await dns.lookup(hostname)
I see why you used `var` here. It’s clever, but I’m not sure if I like it. Personally I would declare it above the `try` block.

2023-09-18 15:17 UTC, remcohaszing commented on lib/safe-http-client.js
> +import {fetch} from 'undici'
I know the [`fetch`](https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch) global is technically experimental in Node.js, but I wouldn’t mind using that instead.

2023-09-18 15:17 UTC, remcohaszing commented on lib/safe-http-client.js
> +    }
Why don’t we allow another redirect until we detect a loop or invalid redirect URL?

2023-09-18 15:17 UTC, remcohaszing commented on lib/server.js
> +   */
The linked video sparked a lot of discussion on Twitter. There isn’t really a general consensus on this topic for application code. For library code it’s different.

[A quote from the video](https://www.youtube.com/watch?v=nwSe95uFN8E&t=152s):

> If you’re writing library code, you should always declare return types.

This gives you more control over the types that TypeScript will generate.

b) Let’s remove `@public`. Methods are public by default.

2023-09-18 15:17 UTC, remcohaszing commented on lib/server.js
> +    const paths = url.parse(req.url || '')?.path?.split('/')
[`url.parse`](https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost) is deprecated. Let’s use `new URL()` instead.

2023-09-18 15:17 UTC, remcohaszing commented on lib/server.js
> +        return this.write(res, 500, msg)
Leaking error messages can be risky.

```suggestion
        return this.write(res, 500, 'Internal server error')
```

It may be useful to log it though.

```suggestion
        console.error(err)
        return this.write(res, 500, 'Internal server error')
```

Also the error might not be an instance of `Error`. This also needs to be handled.

2023-09-18 15:17 UTC, remcohaszing commented on lib/server.js
> +    const decodedUrl = Buffer.from(hex, 'hex').toString()
Nit: This is consistent with code below.

```suggestion
    const decodedUrl = String(Buffer.from(hex, 'hex'))
```

2023-09-18 15:17 UTC, remcohaszing commented on package.json
> +    "typescript": "^5.2.2"
On its own I don’t really think it matters that much which semver range you choose when starting a project. It does become a problem when updating.

I’ve seen packages update their semver ranges, and make a release for it. Then their dependants do the same thing. This can send a wave of pointless automated pull requests by dependency management bots throughout the ecosystem.

I like to keep things simple and consistent and use `^x.0.0` everywhere.

2023-09-18 15:17 UTC, remcohaszing commented on readme.md
> +In Node.js (version 16+), install with [npm][]:
Node.js 16 is past EOL. Should we remove support for it for new projects?

2023-09-18 15:17 UTC, remcohaszing commented on readme.md
> +server.listen(port)
I think the following works to wrap camomile as a middleware. This is a bit more idiomatic, because this way mode servers with a similar interface can be used.

```suggestion
app.use((ctx, next) => {
  if (/^\/files\/.+/.test(ctx.path.toLowerCase())) {
    return camomile.handle(ctx.req, ctx.res)
  }

  return next()
})

app.listen(port)
```

2023-09-19 19:08 UTC, Murderlon commented on readme.md
> +In Node.js (version 16+), install with [npm][]:
```suggestion
In Node.js (version 18+), install with [npm][]:
```

2023-09-19 19:10 UTC, Murderlon commented on lib/safe-http-client.js
> +      var {address} = await dns.lookup(hostname)
I think it's pretty neat, especially compared to this:

```js
    let address
    try {
      ;({address} = await dns.lookup(hostname))
```

2023-09-19 19:12 UTC, Murderlon commented on lib/safe-http-client.js
> +import {fetch} from 'undici'
Removing this in favor of global fetch didn't work as-is. It also can't find `Headers` in Typescript which I need. I think I prefer `undici` for now, it's a small but very solid library by node maintainers as well. If you two feel strongly I can investigate further 👍

2023-09-19 19:13 UTC, Murderlon commented on lib/safe-http-client.js
> +    }
I think we should indeed support multiple redirects.

2023-09-20 19:43 UTC, remcohaszing commented on lib/safe-http-client.js
> +import {fetch} from 'undici'
If it does make a difference, then by all means keep using `undici` :+1:

2023-09-20 19:44 UTC, remcohaszing commented on lib/safe-http-client.js
> +      var {address} = await dns.lookup(hostname)
The more I look at it, the more I like it. Let’s keep it.

2023-09-20 19:45 UTC, remcohaszing approved these changes

2023-09-24 19:13 UTC, wooorm commented on index.js
> +export {Server} from './lib/server.js'
Q: forgot if I asked before, but should this be `Server`? Should we use `Camomile` or so?

2023-09-24 19:13 UTC, wooorm commented on readme.md
> +This package is fully typed with [TypeScript][].
Should this export types? Such as `Options`?

2023-09-28 08:24 UTC, Murderlon commented on readme.md
> +This package is fully typed with [TypeScript][].
I'm not sure how with JSDoc, I can't export types from JS and the `index.d.ts` is generated and ignored by git?

2023-09-28 08:32 UTC, wooorm commented on readme.md
> +This package is fully typed with [TypeScript][].
Almost all of our packages export types. The JSDoc you write in JS results in exported types. Here is an example: https://github.com/rehypejs/rehype-sanitize/blob/main/index.js

To learn more about JSDoc, I recommend looking through what `.d.ts` files.

2023-09-28 08:34 UTC, remcohaszing commented on readme.md
> +This package is fully typed with [TypeScript][].
You can’t really re-export types, but you can create a type alias which behaves mostly similar.

In `index.js`:

```js
/**
 * @typedef {import('./lib/server.js').Options} Options
 */
```

2023-09-28 08:35 UTC, wooorm commented on readme.md
> +This package is fully typed with [TypeScript][].
I think only options is useful? So something like: `/** {@typedef {import('./lib/index.js').Options} Options */`

2023-10-04 23:38 UTC, wooorm commented
I think this is good to go now @Murderlon? Do you want to merge this, shall I do it?
Can I help you with the invoice? (Perhaps this can be discussed on the rfc?)

2023-10-05 01:00 UTC, ChristianMurphy approved these changes

2023-10-05 07:24 UTC, merged

2023-11-20 16:08 UTC, wooorm commented
we got the npm name, released! https://github.com/rehypejs/camomile/releases/tag/1.0.0

2023-11-20 16:27 UTC, JounQin commented
Maybe a stupid question, as a non-native English person, I don't quite get why `camomile` is chosen to be the package name? How does it relate to what it does under the hood? And when I want to add such feature in my app, how can I get to know I should use `camomile` instead of other tools.

2023-11-20 16:45 UTC, wooorm commented
The original project that is unmaintained was called "camo", which is a shortening of camouflage.
This package name also starts with camo, so it's a play on that related work.

In the readme you can find a section "when should I use this?" which answers your second question!

2023-11-20 16:53 UTC, JounQin commented
OK, actually I mean the discoverability of the package. Usually projects under `rehypejs` use `rehype-x` (x is exactly what it does), right?

2023-11-20 16:59 UTC, Murderlon commented
It's a bit of an outlier indeed, but in this case the `rehype` prefix would be more confusing as it implies it being a plugin. Since it's a server, which is completely different from anything else in this org, a different name makes sense. And with a different name why not a wordplay on what it was inspired by :)

2023-11-20 17:05 UTC, JounQin commented
My point is still the discoverability of the package. I'm fine with name without `rehype-`. 😂

But if you think `keywords` in `package.json` is already fine, that's OK to me either.

2023-11-20 18:14 UTC, wooorm commented
Yes, we cannot use `rehype-`, that means plugins/presets. This is something else.

Choosing a meaningful name is nice for something like `node-fetch` for `fetch`. But when there isn’t really one word, or that name is already taken, I like using a fun name, a play on words.
Like `undici` for fetching.
Or MDX, or remark.

I don’t worry about discoverability. The keywords and description and the partial match of `camo` in `camomile` are fine.
And a link in the related project [`rehype-github-image`](https://github.com/rehypejs/rehype-github/tree/main/packages/image) soon, should do the trick!